# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  TF_VERSION: 1.0.5
  TFC_WORKSPACE: dev

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: checkout the repo and building the Backend    
        uses: actions/checkout@v2
      - name : building the backend
             
        run: |
          
          cd ./lambda/server
          npm install
          cd -
          
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}
          
      - name: Deploying back-end using terraform
             
        run: |
          
          terraform init
          terraform plan
          terraform apply -auto-approve
         
     
     
     
     
      - name: Building front-end and deploying Frontend using terraform
             
        run: |
            terraform output > ./lambda/client/.env
            cd ./lambda/client
            npm install
            
            CI=false npm run build
            
            terraform init
            terraform plan
            terraform apply -auto-approve
          
            
          
    
  
          
          
          
    
